'use server';
/**
 * @fileOverview A flow to handle admin impersonation of users.
 *
 * - impersonateUser - A function that returns a simulated custom token for a user.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { ADMIN_UID } from '@/lib/firebase';
import { User } from '@/lib/types';

const ImpersonateUserInputSchema = z.object({
  targetUser: z.custom<User>(),
  adminUid: z.string().refine(val => val === ADMIN_UID, {
      message: 'Only the designated admin can perform this action.'
  }).describe('The UID of the admin initiating the action.'),
});
export type ImpersonateUserInput = z.infer<typeof ImpersonateUserInputSchema>;

const ImpersonateUserOutputSchema = z.object({
  // In a real application with a backend (like Cloud Functions), this would be a real
  // custom authentication token generated by the Firebase Admin SDK.
  // For this environment, we will return the user's full data to simulate a login.
  user: z.custom<User>()
});
export type ImpersonateUserOutput = z.infer<typeof ImpersonateUserOutputSchema>;

export async function impersonateUser(input: ImpersonateUserInput): Promise<ImpersonateUserOutput> {
  return impersonateUserFlow(input);
}


const impersonateUserFlow = ai.defineFlow(
  {
    name: 'impersonateUserFlow',
    inputSchema: ImpersonateUserInputSchema,
    outputSchema: ImpersonateUserOutputSchema,
  },
  async ({ targetUser, adminUid }) => {
    // SECURITY CHECK: This check is redundant due to the Zod schema, but it's good practice.
    if (adminUid !== ADMIN_UID) {
      throw new Error('Unauthorized: Only admins can impersonate users.');
    }

    if (!targetUser) {
        throw new Error('User to impersonate not found.');
    }

    // In a real-world scenario with a proper backend (e.g., Firebase Cloud Function),
    // you would use the Firebase Admin SDK here to create a custom token:
    // const customToken = await getAuth(adminApp).createCustomToken(targetUid);
    // And you would return: { customToken }

    // For this prototype environment, we cannot use the Admin SDK.
    // Instead, we will return the full user object. The client will use this
    // to simulate a login by storing it in session storage and navigating.
    // This is NOT a secure practice for a production app but is a necessary
    // workaround for this specific environment.

    return { user: targetUser };
  }
);
